<a href="https://colab.research.google.com/github/subhramannil/MY_LEARNING/blob/main/TRAINING_PIPELINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BASIC DEEP LEARNING NURAL NETWORK FORM USING PYTORCH

1. Load the Dataset
2. Basic Preprocessing
3. Training Process
- Create the model
- Forward Pass
- Loss Calculation
- Backdrop
- Parameters Update
4. Model Evaluation

In [61]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [62]:
df = pd.read_csv('data.csv')
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [63]:
df.shape

(569, 33)

In [64]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)

In [65]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [66]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [67]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [68]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [69]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

We have to label the y_train values

In [70]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [71]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

### Numpy Array to Pytorch Tensors

In [72]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [73]:
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [74]:
y_train_tensor.shape

torch.Size([455])

### We have to define a class

In [75]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.rand(1,dtype=torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [76]:
learning_rate = 0.001
epochs = 25

In [77]:
model = MySimpleNN(X_test_tensor)
model.weights

tensor([[0.0733],
        [0.5177],
        [0.9338],
        [0.7159],
        [0.1207],
        [0.6822],
        [0.9666],
        [0.7643],
        [0.7738],
        [0.3769],
        [0.3302],
        [0.7659],
        [0.1014],
        [0.4088],
        [0.5100],
        [0.5231],
        [0.3503],
        [0.8237],
        [0.4215],
        [0.3380],
        [0.6429],
        [0.2793],
        [0.1620],
        [0.7218],
        [0.2416],
        [0.5711],
        [0.4648],
        [0.0125],
        [0.0127],
        [0.9621]], dtype=torch.float64, requires_grad=True)

In [78]:
model.bias

tensor([0.4379], dtype=torch.float64, requires_grad=True)

### We have to train our model

In [79]:
# 3 Steps are there
# Define a loop
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Backward pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Backward pass
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.305927125527443
Epoch: 1, Loss: 3.305927125527443
Epoch: 2, Loss: 3.304636680242239
Epoch: 2, Loss: 3.304636680242239
Epoch: 3, Loss: 3.30334639764205
Epoch: 3, Loss: 3.30334639764205
Epoch: 4, Loss: 3.3020562778931604
Epoch: 4, Loss: 3.3020562778931604
Epoch: 5, Loss: 3.3007663211703515
Epoch: 5, Loss: 3.3007663211703515
Epoch: 6, Loss: 3.2994765276452975
Epoch: 6, Loss: 3.2994765276452975
Epoch: 7, Loss: 3.2981868974811523
Epoch: 7, Loss: 3.2981868974811523
Epoch: 8, Loss: 3.2968974308517662
Epoch: 8, Loss: 3.2968974308517662
Epoch: 9, Loss: 3.2956081279275784
Epoch: 9, Loss: 3.2956081279275784
Epoch: 10, Loss: 3.2943189888840063
Epoch: 10, Loss: 3.2943189888840063
Epoch: 11, Loss: 3.293030013879384
Epoch: 11, Loss: 3.293030013879384
Epoch: 12, Loss: 3.2917412030935065
Epoch: 12, Loss: 3.2917412030935065
Epoch: 13, Loss: 3.290452556693716
Epoch: 13, Loss: 3.290452556693716
Epoch: 14, Loss: 3.2891640748573563
Epoch: 14, Loss: 3.2891640748573563
Epoch: 15, Loss: 3.2878757577420785
Epoch: 15, Loss: 3.2878757577420785
Epoch: 16, Loss: 3.286587605528309
Epoch: 16, Loss: 3.286587605528309
Epoch: 17, Loss: 3.285299618384335
Epoch: 17, Loss: 3.285299618384335
Epoch: 18, Loss: 3.2840117964811375
Epoch: 18, Loss: 3.2840117964811375
Epoch: 19, Loss: 3.282724139985135
Epoch: 19, Loss: 3.282724139985135
Epoch: 20, Loss: 3.281436649073735
Epoch: 20, Loss: 3.281436649073735
Epoch: 21, Loss: 3.280149323915033
Epoch: 21, Loss: 3.280149323915033
Epoch: 22, Loss: 3.278862164682485
Epoch: 22, Loss: 3.278862164682485
Epoch: 23, Loss: 3.277575171540861
Epoch: 23, Loss: 3.277575171540861
Epoch: 24, Loss: 3.2762883446701916
Epoch: 24, Loss: 3.2762883446701916
Epoch: 25, Loss: 3.2750016842267766
Epoch: 25, Loss: 3.2750016842267766

In [80]:
model.weights

tensor([[ 8.3105e-01],
        [ 4.8762e-01],
        [ 8.4119e-01],
        [ 7.2171e-01],
        [ 5.5119e-01],
        [ 4.5651e-01],
        [ 5.6208e-02],
        [ 6.4380e-02],
        [ 8.3472e-01],
        [ 2.8991e-01],
        [ 6.3931e-01],
        [ 7.0644e-01],
        [ 3.1471e-01],
        [ 8.0307e-01],
        [ 3.4609e-01],
        [ 3.5430e-01],
        [ 4.6853e-01],
        [ 3.3031e-01],
        [ 8.6825e-01],
        [ 1.1737e-01],
        [ 3.1410e-01],
        [ 3.6868e-01],
        [ 7.5094e-01],
        [-2.3733e-03],
        [-1.5910e-03],
        [ 6.2798e-01],
        [ 5.2308e-01],
        [ 5.7508e-01],
        [-1.6569e-04],
        [ 4.6318e-01]], dtype=torch.float64, requires_grad=True)

In [81]:
model.bias

tensor([0.4702], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [82]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5193905830383301

# Lets improve the model

## Definning the model

In [83]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [84]:
learning_rate = 0.001
epochs = 25

In [85]:
# Convert inputs to Float (float32) to match PyTorch layer defaults
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

# 3 Steps are there
# Define a loop
model = MySimpleNN(X_train_tensor.shape[1])
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Backward pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Backward pass
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.7087145447731018
Epoch: 1, Loss: 0.7087145447731018
Epoch: 2, Loss: 0.7086670398712158
Epoch: 2, Loss: 0.7086670398712158
Epoch: 3, Loss: 0.7086195945739746
Epoch: 3, Loss: 0.7086195945739746
Epoch: 4, Loss: 0.708572268486023
Epoch: 4, Loss: 0.708572268486023
Epoch: 5, Loss: 0.7085250020027161
Epoch: 5, Loss: 0.7085250020027161
Epoch: 6, Loss: 0.7084779143333435
Epoch: 6, Loss: 0.7084779143333435
Epoch: 7, Loss: 0.708430826663971
Epoch: 7, Loss: 0.708430826663971
Epoch: 8, Loss: 0.7083838582038879
Epoch: 8, Loss: 0.7083838582038879
Epoch: 9, Loss: 0.7083370089530945
Epoch: 9, Loss: 0.7083370089530945
Epoch: 10, Loss: 0.708290159702301
Epoch: 10, Loss: 0.708290159702301
Epoch: 11, Loss: 0.7082434892654419
Epoch: 11, Loss: 0.7082434892654419
Epoch: 12, Loss: 0.7081969380378723
Epoch: 12, Loss: 0.7081969380378723
Epoch: 13, Loss: 0.7081503868103027
Epoch: 13, Loss: 0.7081503868103027
Epoch: 14, Loss: 0.7081039547920227
Epoch: 14, Loss: 0.7081039547920227
Epoch: 15, Loss: 0.7080575227737427
Epoch: 15, Loss: 0.7080575227737427
Epoch: 16, Loss: 0.708011269569397
Epoch: 16, Loss: 0.708011269569397
Epoch: 17, Loss: 0.7079651355743408
Epoch: 17, Loss: 0.7079651355743408
Epoch: 18, Loss: 0.7079190611839294
Epoch: 18, Loss: 0.7079190611839294
Epoch: 19, Loss: 0.7078729867935181
Epoch: 19, Loss: 0.7078729867935181
Epoch: 20, Loss: 0.707827091217041
Epoch: 20, Loss: 0.707827091217041
Epoch: 21, Loss: 0.7077813148498535
Epoch: 21, Loss: 0.7077813148498535
Epoch: 22, Loss: 0.707735538482666
Epoch: 22, Loss: 0.707735538482666
Epoch: 23, Loss: 0.7076898813247681
Epoch: 23, Loss: 0.7076898813247681
Epoch: 24, Loss: 0.7076442837715149
Epoch: 24, Loss: 0.7076442837715149
Epoch: 25, Loss: 0.707598865032196
Epoch: 25, Loss: 0.707598865032196

In [86]:
model.linear.weight

Parameter containing:
tensor([[ 0.0776,  0.0915, -0.0726, -0.0570,  0.1763,  0.0563, -0.0716,  0.1702,
         -0.1232, -0.0377,  0.0229,  0.0485, -0.0609, -0.1034,  0.0797, -0.1084,
          0.1738,  0.1573, -0.0575,  0.0509,  0.1821, -0.0805, -0.1299, -0.1783,
         -0.1509,  0.0730, -0.1005, -0.0911, -0.0342,  0.1515]],
       requires_grad=True)

In [87]:
model.linear.bias

Parameter containing:
tensor([-0.0328], requires_grad=True)

WE ARE NOT USING PERSONAL LOSS FUNCTION HERE NOW, USE BCSLoss.

In [88]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

learning_rate = 0.01
epochs = 25

loss_function = nn.BCELoss()

# Convert inputs to Float (float32) to match PyTorch layer defaults
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

# 3 Steps are there
# Define a loop
model = MySimpleNN(X_train_tensor.shape[1])
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculate
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Backward pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Backward pass
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6731818914413452
Epoch: 1, Loss: 0.6731818914413452
Epoch: 2, Loss: 0.6551920771598816
Epoch: 2, Loss: 0.6551920771598816
Epoch: 3, Loss: 0.6382280588150024
Epoch: 3, Loss: 0.6382280588150024
Epoch: 4, Loss: 0.6222228407859802
Epoch: 4, Loss: 0.6222228407859802
Epoch: 5, Loss: 0.607111930847168
Epoch: 5, Loss: 0.607111930847168
Epoch: 6, Loss: 0.5928340554237366
Epoch: 6, Loss: 0.5928340554237366
Epoch: 7, Loss: 0.5793313384056091
Epoch: 7, Loss: 0.5793313384056091
Epoch: 8, Loss: 0.5665498375892639
Epoch: 8, Loss: 0.5665498375892639
Epoch: 9, Loss: 0.554439127445221
Epoch: 9, Loss: 0.554439127445221
Epoch: 10, Loss: 0.5429524183273315
Epoch: 10, Loss: 0.5429524183273315
Epoch: 11, Loss: 0.5320464372634888
Epoch: 11, Loss: 0.5320464372634888
Epoch: 12, Loss: 0.5216810703277588
Epoch: 12, Loss: 0.5216810703277588
Epoch: 13, Loss: 0.5118195414543152
Epoch: 13, Loss: 0.5118195414543152
Epoch: 14, Loss: 0.5024278163909912
Epoch: 14, Loss: 0.5024278163909912
Epoch: 15, Loss: 0.4934743642807007
Epoch: 15, Loss: 0.4934743642807007
Epoch: 16, Loss: 0.48493054509162903
Epoch: 16, Loss: 0.48493054509162903
Epoch: 17, Loss: 0.4767695367336273
Epoch: 17, Loss: 0.4767695367336273
Epoch: 18, Loss: 0.4689669907093048
Epoch: 18, Loss: 0.4689669907093048
Epoch: 19, Loss: 0.4615001976490021
Epoch: 19, Loss: 0.4615001976490021
Epoch: 20, Loss: 0.45434829592704773
Epoch: 20, Loss: 0.45434829592704773
Epoch: 21, Loss: 0.44749200344085693
Epoch: 21, Loss: 0.44749200344085693
Epoch: 22, Loss: 0.4409136474132538
Epoch: 22, Loss: 0.4409136474132538
Epoch: 23, Loss: 0.43459659814834595
Epoch: 23, Loss: 0.43459659814834595
Epoch: 24, Loss: 0.42852574586868286
Epoch: 24, Loss: 0.42852574586868286
Epoch: 25, Loss: 0.4226868450641632
Epoch: 25, Loss: 0.4226868450641632

In [89]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

learning_rate = 0.08
epochs = 25

loss_function = nn.BCELoss()

# Convert inputs to Float (float32) to match PyTorch layer defaults
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

# 3 Steps are there
# Define a loop
model = MySimpleNN(X_train_tensor.shape[1])

#Define an optimiser
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculate
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Backward pass
  optimizer.zero_grad()

  # Backward pass
  loss.backward()

  # Parameters Update
  optimizer.step()

  #Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.5473421216011047
Epoch: 1, Loss: 0.5473421216011047
Epoch: 2, Loss: 0.47163185477256775
Epoch: 2, Loss: 0.47163185477256775
Epoch: 3, Loss: 0.42021292448043823
Epoch: 3, Loss: 0.42021292448043823
Epoch: 4, Loss: 0.38282644748687744
Epoch: 4, Loss: 0.38282644748687744
Epoch: 5, Loss: 0.354207843542099
Epoch: 5, Loss: 0.354207843542099
Epoch: 6, Loss: 0.33144018054008484
Epoch: 6, Loss: 0.33144018054008484
Epoch: 7, Loss: 0.31278619170188904
Epoch: 7, Loss: 0.31278619170188904
Epoch: 8, Loss: 0.29714637994766235
Epoch: 8, Loss: 0.29714637994766235
Epoch: 9, Loss: 0.283789724111557
Epoch: 9, Loss: 0.283789724111557
Epoch: 10, Loss: 0.27221018075942993
Epoch: 10, Loss: 0.27221018075942993
Epoch: 11, Loss: 0.2620454728603363
Epoch: 11, Loss: 0.2620454728603363
Epoch: 12, Loss: 0.25302889943122864
Epoch: 12, Loss: 0.25302889943122864
Epoch: 13, Loss: 0.24495933949947357
Epoch: 13, Loss: 0.24495933949947357
Epoch: 14, Loss: 0.23768198490142822
Epoch: 14, Loss: 0.23768198490142822
Epoch: 15, Loss: 0.23107559978961945
Epoch: 15, Loss: 0.23107559978961945
Epoch: 16, Loss: 0.2250436246395111
Epoch: 16, Loss: 0.2250436246395111
Epoch: 17, Loss: 0.2195081263780594
Epoch: 17, Loss: 0.2195081263780594
Epoch: 18, Loss: 0.21440541744232178
Epoch: 18, Loss: 0.21440541744232178
Epoch: 19, Loss: 0.209682896733284
Epoch: 19, Loss: 0.209682896733284
Epoch: 20, Loss: 0.20529653131961823
Epoch: 20, Loss: 0.20529653131961823
Epoch: 21, Loss: 0.20120930671691895
Epoch: 21, Loss: 0.20120930671691895
Epoch: 22, Loss: 0.19738972187042236
Epoch: 22, Loss: 0.19738972187042236
Epoch: 23, Loss: 0.19381076097488403
Epoch: 23, Loss: 0.19381076097488403
Epoch: 24, Loss: 0.19044910371303558
Epoch: 24, Loss: 0.19044910371303558
Epoch: 25, Loss: 0.18728454411029816
Epoch: 25, Loss: 0.18728454411029816