<a href="https://colab.research.google.com/github/subhramannil/MY_LEARNING/blob/main/TRAINING_PIPELINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BASIC DEEP LEARNING NURAL NETWORK FORM USING PYTORCH

1. Load the Dataset
2. Basic Preprocessing
3. Training Process
- Create the model
- Forward Pass
- Loss Calculation
- Backdrop
- Parameters Update
4. Model Evaluation

In [24]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [25]:
df = pd.read_csv('data.csv')
df

           id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [26]:
df.shape

(569, 33)

In [27]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)

In [28]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [29]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [30]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [32]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

We have to label the y_train values

In [33]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [34]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

### Numpy Array to Pytorch Tensors

In [35]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [36]:
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [37]:
y_train_tensor.shape

torch.Size([455])

### We have to define a class

In [49]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.rand(1,dtype=torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [54]:
learning_rate = 0.001
epochs = 25

In [51]:
model = MySimpleNN(X_test_tensor)
model.weights

tensor([[0.1751],
        [0.2681],
        [0.5440],
        [0.8179],
        [0.4471],
        [0.8134],
        [0.1127],
        [0.9547],
        [0.6310],
        [0.4708],
        [0.3050],
        [0.0907],
        [0.4204],
        [0.6341],
        [0.1181],
        [0.8034],
        [0.0289],
        [0.3785],
        [0.8700],
        [0.2391],
        [0.4810],
        [0.6708],
        [0.2602],
        [0.7791],
        [0.5331],
        [0.9455],
        [0.3956],
        [0.5669],
        [0.4489],
        [0.2156]], dtype=torch.float64, requires_grad=True)

In [52]:
model.bias

tensor([0.2289], dtype=torch.float64, requires_grad=True)

### We have to train our model

In [55]:
# 3 Steps are there
# Define a loop
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Loss Calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Backward pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Backward pass
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.297105928921151
Epoch: 1, Loss: 3.297105928921151
Epoch: 2, Loss: 3.2957584212469597
Epoch: 2, Loss: 3.2957584212469597
Epoch: 3, Loss: 3.2944110765582018
Epoch: 3, Loss: 3.2944110765582018
Epoch: 4, Loss: 3.2930638950529683
Epoch: 4, Loss: 3.2930638950529683
Epoch: 5, Loss: 3.291716876940711
Epoch: 5, Loss: 3.291716876940711
Epoch: 6, Loss: 3.290370022424395
Epoch: 6, Loss: 3.290370022424395
Epoch: 7, Loss: 3.289023331708377
Epoch: 7, Loss: 3.289023331708377
Epoch: 8, Loss: 3.2876768049992067
Epoch: 8, Loss: 3.2876768049992067
Epoch: 9, Loss: 3.286330442499556
Epoch: 9, Loss: 3.286330442499556
Epoch: 10, Loss: 3.2849842444173403
Epoch: 10, Loss: 3.2849842444173403
Epoch: 11, Loss: 3.2836359347833306
Epoch: 11, Loss: 3.2836359347833306
Epoch: 12, Loss: 3.282268088180891
Epoch: 12, Loss: 3.282268088180891
Epoch: 13, Loss: 3.2809004091739813
Epoch: 13, Loss: 3.2809004091739813
Epoch: 14, Loss: 3.2795328979794887
Epoch: 14, Loss: 3.2795328979794887
Epoch: 15, Loss: 3.278165554798833
Epoch: 15, Loss: 3.278165554798833
Epoch: 16, Loss: 3.276798379855988
Epoch: 16, Loss: 3.276798379855988
Epoch: 17, Loss: 3.2754313733537397
Epoch: 17, Loss: 3.2754313733537397
Epoch: 18, Loss: 3.2740645355107527
Epoch: 18, Loss: 3.2740645355107527
Epoch: 19, Loss: 3.2726978665376287
Epoch: 19, Loss: 3.2726978665376287
Epoch: 20, Loss: 3.2713313666421633
Epoch: 20, Loss: 3.2713313666421633
Epoch: 21, Loss: 3.2699650360463783
Epoch: 21, Loss: 3.2699650360463783
Epoch: 22, Loss: 3.2685988749521915
Epoch: 22, Loss: 3.2685988749521915
Epoch: 23, Loss: 3.267232883585826
Epoch: 23, Loss: 3.267232883585826
Epoch: 24, Loss: 3.2658670621543946
Epoch: 24, Loss: 3.2658670621543946
Epoch: 25, Loss: 3.264501410872286
Epoch: 25, Loss: 3.264501410872286

In [56]:
model.weights

tensor([[ 7.0531e-01],
        [ 1.4089e-01],
        [ 8.2434e-02],
        [ 2.9626e-01],
        [ 6.1263e-01],
        [ 1.8215e-01],
        [ 2.2569e-01],
        [ 4.6456e-01],
        [ 1.6063e-01],
        [ 3.4401e-01],
        [ 5.4635e-01],
        [ 7.7926e-01],
        [ 9.4418e-02],
        [ 7.4673e-01],
        [ 6.9456e-01],
        [ 5.5325e-02],
        [ 4.2244e-02],
        [ 4.2460e-01],
        [ 2.9008e-01],
        [-4.6514e-04],
        [ 4.4914e-01],
        [ 2.6167e-01],
        [ 5.3507e-01],
        [ 4.8121e-01],
        [ 8.3246e-01],
        [ 8.0615e-01],
        [ 7.7313e-01],
        [ 9.0199e-01],
        [ 6.2893e-01],
        [ 2.7691e-01]], dtype=torch.float64, requires_grad=True)

In [57]:
model.bias

tensor([0.7747], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [64]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5193905830383301